# Generated by Django 6.0.6 on 2026-06-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reputation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogsTransfers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user", models.CharField(max_length=100)),
                ("to_user", models.CharField(max_length=100)),
                ("reputation", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
